version: '3'

services:
  HackTheDAO:
    image: localhost:56156/HackTheDAO
    build:
      context: ../../../ # do not change
      dockerfile: Challenges/Cryptography/HackTheDAO/Dockerfile
    networks:
      nw0:
    deploy:
      resources:
        limits:
          memory: 200m
          cpus: '0.1'

networks:
  nw0:
    external: true