[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
remappings = ["@src=src/contracts"]
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
